### ISSUE TITLE
Yo what happened

### ISSUE THREAD

**Issue by pazza2234** [arichornlover/arichornlover.github.io#10]
Idk if your archicorn but you know a lot about them. There repos just went poof what happened?

**Comment by arichornlover** [comment]
Well, I changed the name of my GitHub username and than I changed almost all of my repositories to only work with the my new username, I’m sorry if you thought all of my repositories that old my old username disappear 😅

**Comment by arichornlover** [comment]
I just fixed the old url https://arichorn.github.io/
it’s been made to redirect to this repo, if that’s what you wanted!

**Comment by pazza2234** [comment]
@arichornlover  Thanks sorry for the slow response. Also just want to say holy sh*t I can’t live with out uyou enhanced anymore that’s how good it is. You are a mega mind and thanks for keeping it free for everyone.

**Comment by pazza2234** [comment]
Also what’s the new username?

**Comment by arichornlover** [comment]
> Also what’s the new username?

arichornlover?
