### ISSUE TITLE
apps2.json no longer compatible with SideStore

### ISSUE THREAD

**Issue by Macleykun** [arichornlover/arichornlover.github.io#6]
Heya,

im sorry to report, but I received last week the message that the format is incorrect for the apps2.json file in SideStore.

is it due to the beta AltStore feature?

**Comment by arichornlover** [comment]
It’s compatible. It was under a different name but it should be back to being apps2.json now.

**Comment by Macleykun** [comment]
aah i see thanks!
say, is it normal to see each app twice? I also didn't saw the new update come in:
![IMG_0910](https://github.com/arichorn/arichorn.github.io/assets/26381427/640a6c79-de43-445a-81db-17bd12968c6d)

**Comment by arichornlover** [comment]
The heck? I don’t remember having duplicates? I’ll check it out

**Comment by Macleykun** [comment]
heya fam,
I think it's b/c of the way the json is updated, here's an example that seems to work for me when testing:
https://github.com/Balackburn/YTLitePlusAltstore/commit/da95c0b6e67b1f663cc3d37b99ee87c9b8977682

I do have to confess that i've oriented myself on the various version of the tweaked youtube space, and found out that youtubelistplus is the most suited for me personally. As i can enable VP9 engine withoud any slow downs (not even in PIP). Eeverything is in the settings menu which i like aswell.

Combined with the automatic releases that straight go into sidestore, makes it more beneficial for me to sadly switch over to:
https://github.com/Balackburn/YTLitePlus

I do want to thank you for all your hard work and hope your version superseeds ytliteplus oneday!

**Comment by arichornlover** [comment]
YTLitePlus is better then uYouPlus, uYouPlusExtra  & YouTubeRebornPlus so you definitely did the right thing
