### ISSUE TITLE
Bump version identifiers for new releases with the same YouTube version

### ISSUE THREAD

**Issue by aaronliu0130** [arichornlover/arichornlover.github.io#8]
I can't update to the new -F2 version from SideStore either because the version identifier is still the same or the release date is still the same. Could the version identifier be bumped?

**Comment by arichornlover** [comment]
If I bump the version identifer then Altstore won’t allow anyone to download the ipa. It should be alright with the release you have.

**Comment by aaronliu0130** [comment]
Hmm, that sounds weird. Would bumping the release date do anything?

**Comment by arichornlover** [comment]
Nope, I recently just tried that, it did no effect? I probably think the developer of Altstore (Riley) didn’t expect re-releases under the same App Version? I do re-releases because YouTube takes forever to do an app update.

**Comment by aaronliu0130** [comment]
Hmm. I presume changing the version of the compiled IPA itself is also out the window?

**Comment by arichornlover** [comment]
I don’t think changing the version to include -F2 in the json is a good idea. It depends on the app version from the App Store I believe?

**Comment by aaronliu0130** [comment]
Could there be like an extra fourth digit?

**Comment by aaronliu0130** [comment]
i wan' redesigned settings :(

**Comment by arichornlover** [comment]
when google finally releases v19.xx.x then i could do a new release that includes both v18.49.3-F2 & v18.49.3-F3 changes 😭

**Comment by arichornlover** [comment]
Try now, YouTube finally updated their app ;)
so hopefully you can update!

**Comment by aaronliu0130** [comment]
It's a new entry in the store now instead of an update for some reason?

![IMG_2749](https://github.com/arichorn/arichorn.github.io/assets/11874211/30171fe1-58d2-4a71-8a6c-c58a61d63481)

**Comment by arichornlover** [comment]
Alright, I’ll undo the name change.

**Comment by aaronliu0130** [comment]
There was another name change? Both of these say "uYouEnhanced" though, and when v18 is installed it says the top one is installed but not the bottom one.

**Comment by arichornlover** [comment]
Was wondering if it says “uYouPlusExtra” again, and now does it go back to showing only 1 app? If so then that could be the potential cause. 😕

**Comment by aaronliu0130** [comment]
Now, v19, which is installed, makes "uYouPlusExtra" installed while there is still a separate entry for uYouEnhanced which is v18

**Comment by aaronliu0130** [comment]
I can't reproduce from the web interface, maybe it's just me? Anyways I think maybe we should change it back to uYouEnhanced 😅

**Comment by arichornlover** [comment]
Alright

**Comment by aaronliu0130** [comment]
> There was another name change? Both of these say "uYouEnhanced" though, and when v18 is installed it says the top one is installed but not the bottom one.

Figured out the reason: I was using that ~~impostor (/j)~~ arichorn's source, not arichornlover's!

**Comment by aaronliu0130** [comment]
Though hopefully releases with the same YT version can still be upgraded to
